#!/usr/bin/env bash
#
# setup-anchors.sh — install/build the gauntlet anchor engines + nets (macOS).
#
# Reproduces the two anchor pools scripts/gauntlet.sh uses, and (re)writes the
# roster files with absolute paths for THIS machine. Idempotent: skips anything
# already present. Everything lands under ~/chess-engines (outside the repo).
#
#   Maia pool (human Lichess Elo): lc0 + maia-1100..1900 nets, run at nodes=1.
#   CCRL pool (engine Elo):        Cinnamon's CCRL-rated versions, cross-compiled
#                                  for x86_64 (their bitboards use x86 inline asm,
#                                  so they don't build natively on Apple Silicon)
#                                  and run via Rosetta 2.
#   Ordo (optional):               rating calculator for the rigorous cross-check,
#                                  built with the macOS spinlock->mutex fallback.
#
# Prereqs: brew install stockfish lc0 ; Rosetta 2 (softwareupdate --install-rosetta);
#          Xcode command-line tools (clang, git, make), curl.
#
# Usage:  scripts/setup-anchors.sh           # everything
#         scripts/setup-anchors.sh maia      # just one section: maia | ccrl | ordo
set -euo pipefail

REPO="$(git rev-parse --show-toplevel)"
ENGINES="$HOME/chess-engines"
MAIA_DIR="$ENGINES/maia"
WANT="${1:-all}"
mkdir -p "$ENGINES"

do_section() { [[ "$WANT" == "all" || "$WANT" == "$1" ]]; }

# ── Maia pool ─────────────────────────────────────────────────────────────────
if do_section maia; then
    echo ">> Maia nets -> $MAIA_DIR"
    command -v lc0 >/dev/null || { echo "   error: lc0 not found (brew install lc0)"; exit 1; }
    mkdir -p "$MAIA_DIR"
    : > "$REPO/scripts/anchors-maia.txt"
    {
        echo "# Maia roster (HUMAN / Lichess Elo) — generated by scripts/setup-anchors.sh."
        echo "# lc0 + Maia nets at nodes=1. Do NOT merge with anchors-ccrl.txt (different pool)."
        echo "#   name | rating | cmd | verbatim fastchess -engine tokens"
    } >> "$REPO/scripts/anchors-maia.txt"
    for elo in 1100 1300 1500 1700 1900; do
        net="$MAIA_DIR/maia-$elo.pb.gz"
        if [[ ! -s "$net" ]]; then
            curl -fsSL -o "$net" "https://raw.githubusercontent.com/CSSLab/maia-chess/master/maia_weights/maia-$elo.pb.gz"
            echo "   downloaded maia-$elo"
        else echo "   have maia-$elo"; fi
        echo "maia$elo | $elo | lc0 | option.WeightsFile=$net nodes=1" >> "$REPO/scripts/anchors-maia.txt"
    done
    echo "   wrote scripts/anchors-maia.txt"
fi

# ── CCRL pool (Cinnamon, x86_64 via Rosetta) ──────────────────────────────────
if do_section ccrl; then
    echo ">> Cinnamon CCRL anchors (x86_64 via Rosetta) -> $ENGINES"
    arch -x86_64 true 2>/dev/null || { echo "   error: Rosetta 2 not available (softwareupdate --install-rosetta)"; exit 1; }
    SRC="$ENGINES/cinnamon-src"
    [[ -d "$SRC" ]] || git clone --quiet https://github.com/gekomad/cinnamon "$SRC"
    : > "$REPO/scripts/anchors-ccrl.txt"
    {
        echo "# CCRL roster (ENGINE / CCRL Blitz Elo) — generated by scripts/setup-anchors.sh."
        echo "# Cinnamon's CCRL-rated versions, cross-compiled x86_64 + run via Rosetta 2."
        echo "# Do NOT merge with anchors-maia.txt (different pool)."
        echo "#   name | rating | cmd | verbatim fastchess -engine tokens"
    } >> "$REPO/scripts/anchors-ccrl.txt"
    # tag -> CCRL Blitz rating (https://computerchess.org.uk/ccrl/404/)
    for spec in "v2.2a:2071:cinnamon2.2a" "v2.3.4:2212:cinnamon2.3"; do
        tag="${spec%%:*}"; rest="${spec#*:}"; rating="${rest%%:*}"; name="${rest#*:}"
        out="$ENGINES/cinnamon-$tag-x86"
        if [[ ! -x "$out" ]]; then
            ( cd "$SRC/src" && git -C "$SRC" checkout -q "$tag" \
              && make clean >/dev/null 2>&1 \
              && make cinnamon64-modern COMP="clang++ -arch x86_64" LIBS="-lpthread" >/dev/null 2>&1 \
              && cp cinnamon "$out" )
            echo "   built $tag -> $out"
        else echo "   have $tag"; fi
        echo "$name | $rating | $out" >> "$REPO/scripts/anchors-ccrl.txt"
    done
    git -C "$SRC" checkout -q v2.5 2>/dev/null || true
    echo "   wrote scripts/anchors-ccrl.txt"
fi

# ── Ordo (optional rating calculator) ─────────────────────────────────────────
if do_section ordo; then
    if command -v ordo >/dev/null; then
        echo ">> ordo already on PATH — skipping"
    else
        echo ">> building ordo (macOS spinlock->mutex fallback)"
        ORD="$ENGINES/Ordo"
        [[ -d "$ORD" ]] || git clone --quiet https://github.com/michiguel/Ordo "$ORD"
        ( cd "$ORD" && make clean >/dev/null 2>&1; \
          make CC=clang CFLAGS="-DNDEBUG -DMY_SEMAPHORES -DNSPINLOCKS -flto -I myopt -I sysport" >/dev/null 2>&1 )
        cp "$ORD/ordo" /opt/homebrew/bin/ordo && echo "   installed ordo -> /opt/homebrew/bin/ordo"
    fi
fi

echo ">> done. Run:  MODE=file ANCHORS=scripts/anchors-ccrl.txt scripts/gauntlet.sh"
echo "          or:  MODE=file ANCHORS=scripts/anchors-maia.txt scripts/gauntlet.sh"
